### ISSUE TITLE
BTCPay Settings not saved after editing them.

### ISSUE THREAD

**Issue by TheGreatOneYouKnow** [btcpayserver/opencart#12]
Hello,
BTCPay is not working in the latest version of OpenCart 4.0.2.3. It doesn't want to save settings in the OpenCart BTCPay settings. In error log is this:

2023-09-21 17:52:27 - PHP Warning: Undefined array key "payment_btcpay_url"
File: /home/***/***/extension/btcpay/admin/controller/payment/btcpay.php
Line: 108

2023-09-21 17:52:27 - PHP Warning: Undefined array key "payment_btcpay_api_auth_token"
File: /home/***/***/extension/btcpay/admin/controller/payment/btcpay.php
Line: 109

2023-09-21 17:52:27 - PHP Warning: Undefined array key "payment_btcpay_btcpay_storeid"
File: /home/***/***/extension/btcpay/admin/controller/payment/btcpay.php
Line: 110

2023-09-21 17:52:27 - BTCPayServer\Client\AbstractClient::__construct(): Argument #1 ($baseUrl) must be of type string, null given, called in /home/***/***/extension/btcpay/admin/controller/payment/btcpay.php on line 113

Can someone please check it out?
Thanks a lot.

**Comment by NicolasDorier** [comment]
Which version of plugin are you running?

**Comment by TheGreatOneYouKnow** [comment]
With the versions, there is a problem too. I downloaded the latest version from Open Cart: 

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=44269

which is 4.1.0 and it was causing that problem in that version.

But then I've noticed here on github is version 4.2.0: 

https://github.com/btcpayserver/opencart/releases/tag/v4.2.0

so I've downloaded it and installed. But once installed in OpenCart, it shows as version 4.1.0 , NOT as version 4.2.0 and it's causing the same problem anyways.

**Comment by TheGreatOneYouKnow** [comment]
What I have noticed, I had older version of OpenCart 4.0.2.2 and there the BTCPay plugin was working. But after I upgraded OpenCart to 4.0.2.3, ( I had to use this plugin because stock upgrade was not working:https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=45216 )
edits in BTCPay settings stopped being saved.

**Comment by NicolasDorier** [comment]
seems like @ndeet knows what is going on and there was a breaking change in a minor release. He probably is on it.

**Comment by TheGreatOneYouKnow** [comment]
> seems like @ndeet knows what is going on and there was a breaking change in a minor release. He probably is on it.

Any idea how long it could take to fix it? Because new users will not be able to use BTCPay at all, since data entered in the settings won't be saved.

**Comment by ndeet** [comment]
@TheGreatOneYouKnow sorry had no time to upgrade and fix it but will look into it later today likely publish a fix tomorrow, the release I did a few weeks ago was for the breaking change in 4.0.2.0 I hope there was not another breaking change in 4.0.2.3 :roll_eyes:

**Comment by TheGreatOneYouKnow** [comment]
@ndeet great news, thanks a lot.

**Comment by ndeet** [comment]
@TheGreatOneYouKnow just [released v4.2.1](https://github.com/btcpayserver/opencart/releases) which fixes the problem. Not sure why it did not error in the previous versions, I did not see any breaking change upstream on OC but the form was set as if it had file uploads which broke something on processing the ajax request.

**Comment by TheGreatOneYouKnow** [comment]
@ndeet  Great, thanks a lot for a fast fix. Will check it out today.

**Comment by TheGreatOneYouKnow** [comment]
@ndeet  It is working now. Thanks a lot for fixing it.
