### ISSUE TITLE
After configuring according to the official document, a checkout error occurs

### ISSUE THREAD

**Issue by victorok1234** [btcpayserver/opencart#2]
After configuring according to the official document, a checkout error occurs

Warning: Undefined variable $invoice in /extension/btcpay/catalog/controller/payment/btcpay.php on line 101Error: Call to a member function getData() on null in /extension/btcpay/catalog/controller/payment/btcpay.php on line 101

**Comment by ndeet** [comment]
Hi, can you please copy the php and opencart version info from the settings page. And please also check the opencart error logs, they likely contain more context to the error.

**Comment by ndeet** [comment]
Hi again @victorok1234 there was some autoloading problem which has been fixed in the OpenCart 3 version of the plugin. Maybe this also solved your issue? If not please let me know your PHP, OpenCart and plugin versions.

**Comment by ndeet** [comment]
Closing due to no response.
