### ISSUE TITLE
Opencart 4.0.1.1 Issue PHP Warning:  Undefined array key "order_id" 

### ISSUE THREAD

**Issue by kevc978** [btcpayserver/opencart#3]
Hi,

Looking through my error logs on opencart i seem to be receiving the following error:

PHP Warning:  Undefined array key "order_id" in /var/www/html/opencart/upload/extension/btcpay/catalog/controller/payment/btcpay.php on line 141

Any idea how i can fix this?  everything seems to be working except changing status when the order receives at least 1 confirmation

Thanks

**Comment by ndeet** [comment]
Hi @kevc978, sorry for the late reply, did not see the notification.

I just tried to reproduce but was not able to. Could it be that your session of OC timed out when you returned to the order page. The code you mentioned is run after you paid and clicked on the "return to merchant" button on btcpay invoice.

For me the session data contains the order_id:
```
Array
(
    [currency] => USD
    [user_id] => 1
    <-----snip----->
    [order_id] => 7
```

What could happen is if you click on the linked order in the BTCPay Server interface and it will redirect you to the shop page but the session will be outdated and not match. If that is the case you can ignore it.

For order status changing after first confirmation, can you elaborate on that one? 

You can set the invoice to be settled after 1 confirmation in your wallet settings like this:
![image](https://user-images.githubusercontent.com/1136761/210179922-e158c525-5aca-4582-badb-12114aae2f11.png)

Depending on what you set in the BTPay plugin on OC the order status should change accordingly:
![image](https://user-images.githubusercontent.com/1136761/210179947-0ca50ba8-3206-4cbb-abcc-7377e37dbcdd.png)
